Roll20/roll20-api-scripts

- Flight/Flight.js
Related forum thread: https://app.roll20.net/forum/post/1529492/i-couldnt-get-the-flight-api-to-work/#post-1530174
> Fixed Bug - arg0 instead of args0.

- Dynamic Lighting Animation/Dynamic Lighting Animation.js
- Dynamic Lighting Animation/package.json
- Flight/Flight.js
- Flight/package.json
- Flip Tokens/Flip Tokens.js
- Flip Tokens/package.json
- Marking Conditions/Marking Conditions.js
- Marking Conditions/package.json
- Raise Count/Raise Count.js
- Raise Count/package.json
- Store Commands/Store Commands.js
- Store Commands/package.json
See #15 and https://app.roll20.net/forum/post/1529492/i-couldnt-get-the-flight-api-to-work#post-1529492
While it is the same error, this commit does not modify /Flight, as that file is being fixed by the commit in #15
> fixed args0->arg0 transcription error

- Dynamic Lighting Animation/Dynamic Lighting Animation.js
- Dynamic Lighting Animation/package.json
- Flip Tokens/Flip Tokens.js
- Flip Tokens/package.json
- Marking Conditions/Marking Conditions.js
- Marking Conditions/package.json
- Raise Count/Raise Count.js
- Raise Count/package.json
- Store Commands/Store Commands.js
- Store Commands/package.json
These changes are similar to the boilerplate fixes in #18
> Clean up help dispatch and no-arg crash

- Its A Trap/package.json
- Token Collisions/TokenCollisions.js
- Token Collisions/package.json
TokenCollisions.getFirstCollision now works with tokens of variable radii.
> TokenCollisions.getFirstCollision

- Measure/Measure.js
- Measure/package.json
Fixed this broken script that slipped in with the others. =D
> Prod measure

- EotE Dice Roller/EotE-Dice.js
- EotE Dice Roller/help.txt
- EotE Dice Roller/package.json
> EotE Dice Roller

- MarchingOrder/README.md
- MarchingOrder/marchingOrder.js
- MarchingOrder/package.json
Added MarchingOrder script for specifying order for tokens to follow each other.
> Added MarchingOrder script for specifying order for tokens to follow each other.

- Numenera_Natha/Help.txt
- Numenera_Natha/Numenera_Natha.js
- Numenera_Natha/package.json
Enables the use of advance rolls and functions in Natha's Numenera
character sheets (both english and french) version 4+. See Help.txt
> Natha's Numenera (v4.0)

- Numenera_Natha/Numenera_Natha.js
- Numenera_Natha/package.json
v4.1: bug correction on npcDamage
The ncpDamage function / !nathanum-npcdmg command could not find the
Health attribute anymore.
> v4.1: bug correction npcDamage / !nathanum-npcdmg

- RandomEncounters/RandomEncounters.js
- RandomEncounters/package.json
Using a Rollable Table with a specific naming pattern, this script rolls
for and prints a possible random encounter to the GM.
> RandomEncounters Skript using Rollable Tables

- TokenNameNumber/TokenNameNumber.js
- TokenNameNumber/package.json
> TokenNameNumber: Updated to version 0.5.2

- HiddenRolls/hidden.js
- RollStats/Help.txt
- RollStats/package.json
- RollStats/stats.js
Also minor change to how we use the permission command so that if that ever fails it'll whisper the GM instead of a name that probably won't exist in the campaign.
> Add script to track and display roll statistics.

- Track V20 Attributes/README.md
- Track V20 Attributes/Track V20 Attributes.js
- Track V20 Attributes/package.json
Script that keeps track of attributes not included by default in the V20 character sheet, allowing them to be used with macros and other scripts.
> Created script to track attributes on the V20 character sheet.

- Track V20 Attributes/Track V20 Attributes.js
Added quotes to version number to avoid potential messiness.
> Stringify version number

- Numenera_Natha/Numenera_Natha.js
Skill level and Assets added to the Initiative roll parameters. API script updated accordingly.
> v4.4 : Skill level & Assets added to Initiative

- Numenera_Natha/Help.txt
- Numenera_Natha/Numenera_Natha.js
- Numenera_Natha/package.json
v4.5: Added skill level to roll parameters (both from sheet and from
macro), and Special damage handling to the damage track/check character
state.
> v4.5 : special damage handling

- GroupInitiative/GroupInitiative.js
- GroupInitiative/package.json
Added Observable Pattern for TurnOrder changes.
> GroupInitiative: Update to version 0.9.7

- GroupInitiative/GroupInitiative.js
- GroupInitiative/package.json
Fixed crash bug with missing attributes.
> GroupInitiative: Update to version 0.9.8

- TableExport/TableExport.js
- TableExport/package.json
> TableExport: Updated to 0.2.0

- CustomStatusMarkers/CustomStatusMarkers.js
- CustomStatusMarkers/README.md
- CustomStatusMarkers/package.json
- PathMath/PathMath.js
Custom status markers can now be graphics.
!listMarkers command
Removed debugging logs.
Better marker icon scaling.
> Custom status markers

- CypherSystemSheet/cyphersystemsheet.js
- CypherSystemSheet/package.json
- Numenera_Natha/package.json
Cypher System Sheet API functions : Enables the applying of stat cost,
auto calculation of PC state and damage track in the Cypher System Sheet
> Cypher System Sheet API functions

- CypherSystemSheet/cyphersystemsheet.js
- Numenera_Natha/Numenera_Natha.js
Numenera tabbed script v4.7
Automatic attributes creation if needed + new function for stat
modifying.
> Numenera tabbed script v4.7 & Cypher System script 1.1

- CypherSystemSheet/cyphersystemsheet.js
- CypherSystemSheet/package.json
Cypher System Sheet script v1.1: added a function to reset the Action roll parameters.
> Cypher System Sheet script v1.1

- Blood-and-Honor/BloodAndHonor.js
Using playerIsGM() now.
Using createObj() instead of the fixed version.
Not going to crash on randomInteger call for moved tokens.
> Blood and Honor: Patch: playerIsGM, createObj, randomInteger crash.

- CypherSystemSheet/cyphersystemsheet.js
- CypherSystemSheet/package.json
Cypher System Sheet script v1.2: Recovery Roll update.
The modStat function can be used to update the Recovery Roll attribute.
> Cypher System Sheet script v1.2: Recovery Roll

- Numenera_Natha/Numenera_Natha.js
- Numenera_Natha/package.json
New "resetAction" paramaters function.
> Numenera script v4.8

- EotE Dice Roller-New/EotE-Dice-Fr.js
- EotE Dice Roller-New/help.txt
- EotE Dice Roller-New/package.json
New script for character sheet for FFG Star Wars RPGs (Eote/AoR/FaD).
French version. Better graph and new options
> New script for character sheet

- ChangeTokenImage/ChangeTokenImage.js
- ChangeTokenImage/package.json
Aaron made some updates to fix some issues, pulling
> Updates to ChangeTokenImage

- Languages/Languages.js
This time it works, users with 1 word names can see the messages
> Fixed the bug this time

- Languages/Languages.js
- Languages/help.txt
this command allows GMs to set the attribute name of their languages on their character sheets
> added !setLanguageTag command for compatability

- Languages/Languages.js
- Languages/help.txt
- Languages/package.json
implements 2 new commands for creating and deleting languages
> Update to version 1.1.0

- HaloMythicUtilities/HaloMythicUtilities.js
- HaloMythicUtilities/help.txt
- HaloMythicUtilities/package.json
Adds a script that allows users to quickly determine hit locations and
special damage results from attacks
> Create Halo Mythic Utilities

- HaloMythicUtilities/HaloMythicUtilities.js
- HaloMythicUtilities/help.txt
- HaloMythicUtilities/package.json
Pierce was essentially being added to damage directly due to a math error
> V1.1 - Fix pierce

- PortesMonstresTresors/package.json
- PortesMonstresTresors/pmt.js
API script for the Portes Monstres Tresors character sheet
> PortesMonstresTresors v1.0

- textTimer/LICENSE
- textTimer/README.md
- textTimer/package.json
- textTimer/textTimer.js
> Adding first working version

- MatrixMath/1.0/matrixMath.js
- MatrixMath/README.md
- MatrixMath/matrixMath.js
- MatrixMath/script.json
Created MatrixMath script, a library for performing mathematical operations for matrices, linear algebra, and 2D affine transformations. Unit tests included.
> Matrix math

- Slide Tokens/1.2/Slide Tokens.js
- Slide Tokens/README.md
- Slide Tokens/script.json
> Update Slide Tokens to v1.2

- Collision Detection/2.2/Collision Detection.js
- Collision Detection/README.md
- Collision Detection/script.json
- Raise Count/2.5/Raise Count.js
- Raise Count/README.md
- Raise Count/script.json
Raise Count, Collision Detection & Slide Tokens
> Update globalconfig support

- Saga Machine Roller/README.md
- Saga Machine Roller/script.json
- Saga Machine Roller/sm_roller.js
Adding companion script for the Against the Dark Yogi and Shadows Over Sol character sheets.
> Companion script for Against the Dark Yogi, Shadows Over Sol

- ItsATrap_theme_GammaWorld7/1.0/TrapTheme.js
- ItsATrap_theme_GammaWorld7/README.md
- ItsATrap_theme_GammaWorld7/script.json
An ItsATrap theme for the Gamma World 7E character sheet.
> Trap Theme - Gamma World 7E

- Pathfinder PCGen Import/PCGenPFImport.js
- Pathfinder PCGen Import/csheet_pathfinder_roll20.txt.ftl
- Pathfinder PCGen Import/script.json
Adding my script from forum post to repository.
https://app.roll20.net/forum/post/2595554/pf-pcgen-output-to-pathfinder-character-sheet/?pageforid=2595649#post-2595649
> Initial commit of Pathfinder PCGen Import

- Page Navigator/1.031/Page Navigator
- Page Navigator/script.json
- ShareVision/1.4/ShareVision.js
- ShareVision/script.json
The first version of my Page Navigator and ShareVision scripts for upload to the Roll 20 one-click API install.
> Page Navigator

- ArsMagica5eStressDie/ArsMagica5eStressDie.js
- ArsMagica5eStressDie/ArsMagica5eStressDie_nomod.js
- ArsMagica5eStressDie/script.json
Added a special die roller for Ars Magica 5e, which uses a multiplicative explode and multistage critical failure system.
> New script for a particular kind of Ars Magica 5e roll

- PortesMonstresTresors/1.4/pmt.js
- PortesMonstresTresors/script.json
> PMT character creation helper v1.4

- RandomEncounters/RandomEncounters.js
Fixed a severe bug and added usage
> RandomEncounters corrected

- Collision Detection/2.2/Collision Detection.js
This is causing an issue on the `warn player & stop at wall` case
> Fix typo on variable name

- ItsATrap_theme_RoleplayingIsMagic4/3.1/TrapTheme.js
- ItsATrap_theme_RoleplayingIsMagic4/README.md
- ItsATrap_theme_RoleplayingIsMagic4/script.json
Fixed a couple bugs in the Roleplaying Is Magic trap theme.
> Trap Theme: Roleplaying Is Magic 3.1

- MythicGM/MythicGM.js
- MythicGM/script.json
Adding  New Script MythicGM to bring the GM emulators rules for Mythic to Roll20.
> Creating New Script MythicGM

- ItsATrap_theme_PathfinderSimple/script.json
I forgot to update the current version of this script to 3.0 last time... oops.
> Trap Theme - Pathfinder Simple 3.0 (fixed script.json)

- Critical/0.1.0/Critical.js
- Critical/Critical.js
- Critical/READ.md
- Critical/script.json
Added Critical script (The brother script to Fumbler).
> Added Critical script (The brother script to Fumbler)

- LightCrumb/0.75/LightCrumb.js
- LightCrumb/LightCrumb.js
- LightCrumb/script.json
Leaves lit, shared-vision trails of torches behind player tokens. Allows
players to see where they've been on maps with dynamic lighting turned
on.
> New Script for 1-Click. LightCrumb

- StatusFX/1.2.1/statusFx.js
- StatusFX/script.json
Fixed an undefined access bug concerning CustomStatusMarkers.
> Status FX 1.2.1

- KABOOM/1.2/KABOOM.js
- TruePageCopy/README.md
- TruePageCopy/TruePageCopy.js
- TruePageCopy/script.json
A script to automatically duplicate page graphics when players use the duplicate page button.
> Adding TruePageCopy.js

- HealthColors/1.4.1/HealthColors.js
- HealthColors/script.json
Added Token update, reworked logic for Token Update execution time.
> 1.4.1 Update

- HealthColors/1.5.1/HealthColors.js
- HealthColors/script.json
Fix for toggle options in special situations resetting aura.
Fix for toggle options in special situations resetting show names.
Added Blue tint/aura overheal.
> 1.5.1 update

- AgoneDice/0.1/AgoneDice.js
- AgoneDice/AgoneDice.js
- AgoneDice/script.json
API script to roll automatically fumble when an 1 is detected from an exploding dice. This script has to be used with Agone-(french) character sheet.
> AutoImploding rolls for Agone-(french) character sheet

- wfrp2e-api/help.txt
- wfrp2e-api/script.json
- wfrp2e-api/wfrp2e-api.js
Per recommendations for auto-install support.
> API scripts and documentation for Havoc's WFRP2E character sheet

- ColoredChatDividers/1.0/coloredChatDividers.js
- ColoredChatDividers/script.json
This is a script I wrote to add dividers at the bottom of player chat messages. This helps break the monotony of the gray text, and more importantly helps differentiate between players when trying to review chat.
> script to add colored dividers between chat messages

- ItsATrap_theme_WoDClassic/3.0/TrapTheme.js
- ItsATrap_theme_WoDClassic/README.md
- ItsATrap_theme_WoDClassic/script.json
To whoever merges this in: In the globalconfig object, please assign this script's user options to the key "itsatrapthemewodc".
> Created Trap Theme for World of Darkness classic

- TurnClock/TurnClock.js
- TurnClock/script.json
Here is a new TurnClock script I'd like to share from my friend @Bastlifa
> TurnClock added

- TotalRolled for AGE/2.0.0/TotalRolled for AGE.js
- TotalRolled for AGE/TotalRolled for AGE.js
- TotalRolled for AGE/script.json
It should work for other systems if they match the format, as this uses the default template.
> Fork of TotalRolled for the new AGE System sheet

- Hourglass/1.0/hourglass.js
- Hourglass/script.json
Adds a minimalist hourglass feature that can be accessed via `!hg` commands in chat.
> Hourglass 1.0

- Hourglass/script.json
> Fixing instructions in script.json

- TotalRolled for AGE/2.1.0/TotalRolled for AGE.js
- TotalRolled for AGE/TotalRolled for AGE.js
- TotalRolled for AGE/script.json
- Added code to whisper the Summary if it was whispered.
> TotalRolled for AGE 2.1

- OneRollEngine/0.2/matchingSets.js
- OneRollEngine/script.json
Added optional argument to sort sets returned by Height.
Changed usage comment on line 13.
Fixed typos.
> One Roll Engine Update

- WelcomePackage/1.1/script.js
- WelcomePackage/script.json
Character creation is delayed along with chat message so that other scripts that initialize characters have a chance to load at startup.
> Welcome Package v1.1

- COFantasy/0.5/COFantasy.js
- COFantasy/0.5/doc.html
- COFantasy/COFantasy.js
- COFantasy/doc.html
and some more skills and spells.
> COFantasy: started to add new classes

- COFantasy/COFantasy.js
- COFantasy/doc.html
- COFantasy/script.json
In addition, corrected the effect of the surveillance skill.
> COFanstasy: Change of interface for the fear effect.

- Genesys-RPG-Roller/1.3.0/Genesys-Dice-Roller.js
- Genesys-RPG-Roller/script.json
Fixed issues of zombie code from SWRPG dice roller
> Updated to version 1.3.0

- CashMaster/0.4.1/CashMaster.js
- CashMaster/CashMaster.js
- CashMaster/README.md
- CashMaster/script.json
Adding my Cashmaster script - a script to manage a party's cash. See [forum](https://app.roll20.net/forum/post/5950228/script-cashmaster-5e-a-simple-script-to-manage-a-partys-money)
> Added Cashmaster 0.4.1

- Genesys-RPG-Roller/1.3.0/Genesys-Dice-Roller.js
- Genesys-RPG-Roller/script.json
Added brackets around the scipt version numbers
> Fixed an issue with the json that caused the script to break

- COFantasy/0.8/COFantasy.js
- COFantasy/0.8/doc.html
- COFantasy/COFantasy.js
- COFantasy/doc.html
Also added more priest and necromancer spells.
> COFantasy: propose a choice of skills when rolling for a carac.

- Bloodied and Dead Status Markers/Bloodied and Dead Status Markers.js
- Bloodied and Dead Status Markers/Help.txt
Added ability for the bar that is read for status to be changed by the user. This allows you to use bar2 and bar3 as well if you desire. Used this for a game, might as well put it up.
> Bloodied and Dead variability update

- Xeohelios' Fire Emblem Tabletop Companion/1.0/FETTC.js
- Xeohelios' Fire Emblem Tabletop Companion/1.1/FETTC.js
- Xeohelios' Fire Emblem Tabletop Companion/script.json
These are companion scripts for the [character sheet of the same name.](https://github.com/Roll20/roll20-character-sheets/tree/master/Xeohelios'%20Fire%20Emblem%20Tabletop)
> Added FETT scripts

- FFG-SWRPG-Dice-Roller/6.4.3/FFG-SWRPG-Dice-Roller.js
Fixes two bugs with downgrading dice
Fix by Bast L.
> FFG-SWRPG-Dice-Roller, Downgrade fix

- PowerCards/3.7.1/PowerCards.js
- PowerCards/script.json
I've taken over the maintenance of the PowerCards API and am working on getting it into the one-click install system.
> Initial Commit to add PowerCards to repository

- Xeohelios' Fire Emblem Tabletop Companion/1.3/FETTC.js
- Xeohelios' Fire Emblem Tabletop Companion/script.json
Battle messages are now formatted with CSS to look much nicer, numerous bugfixes
> Battle Formatting

- Forbidden Lands Dice Roller/FORLDieRoller.js
> Update Forbidden Lands Die Roller

- Xeohelios' Fire Emblem Tabletop Companion/1.3/FETTC.js
- Xeohelios' Fire Emblem Tabletop Companion/script.json
Fixes issue addressed here:
https://github.com/missing-q/emblem20/issues/1
> Quick bugfix

- HeroTracker/1.0/README.md
- HeroTracker/1.0/herotracker.js
- HeroTracker/1.0/script.json
- HeroTracker/README.md
- HeroTracker/herotracker.js
- HeroTracker/script.json
This is my first api.
I'd say go easy on me but won't.  My ego isn't fragile.  All constructive comments are appreciated.
> Initial Release of herotracker

- Xeohelios' Fire Emblem Tabletop Companion/1.5/FETTC.js
- Xeohelios' Fire Emblem Tabletop Companion/script.json
-Allegiance checking for AOE
- Fixed skill levelup message
> Death checking & more

- InspirationTracking/script.json
> updated version

- PowerCards/3.7.6/PowerCards.js
- PowerCards/script.json
Update PowerCards API to 3.7.6, including bug fixes and new formatting features.
> PowerCards Update to 3.7.6

- Hero6Playable/1.0/hero6playable.js
- Hero6Playable/README.md
- Hero6Playable/hero6playable.js
- Hero6Playable/script.json
Initial deployment of Hero6Playable api for use with Hero6Playable character sheet.
> Initial deployment (version 1.0)

- Xeohelios' Fire Emblem Tabletop Companion/1.6.1/FETTC.js
All scripts return if one of the provided characters is not linked to a character sheet.
> Fixed target/selected token id validation

- Xeohelios' Fire Emblem Tabletop Companion/1.7/FETTC.js
- Xeohelios' Fire Emblem Tabletop Companion/script.json
-Please update your skills if you haven't already!
> Radius skills now support multiple stats

- GMSheet/0.1.3/GMSheet.js
- GMSheet/0.1.4/GMSheet.js
- GMSheet/GMSheet.js
- GMSheet/README.md
- GMSheet/script.json
This adds the latest two versions of my GMSheet to the roll20 api repo.
> Add GMSheet 0.1.4

- PowerCards/3.7.9/PowerCards.js
- PowerCards/script.json
Template system, replacement values system, sandbox protection code, bugfixes.
> Updates to PowerCards API Script

- COFantasy/1.05/COFantasy.js
- COFantasy/1.05/doc.html
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/doc.html
> COFantasy: added rage for creatures

- TailsOfEquestriaHelper/1.1/ToEHelper.js
- TailsOfEquestriaHelper/README.md
- TailsOfEquestriaHelper/script.json
Turn on API support for Exploding Hoof rolls when the script starts.
> Tails of Equestria Helper v1.1

- PowerCards/3.8.5/PowerCards.js
- PowerCards/script.json
Update OneClick version of PowerCards to 3.8.5
> Update PowerCards to 3.8.5

- WelcomePackage/1.2/script.js
- WelcomePackage/script.json
Added a method for observing the added character.  Example use:
```
on('ready',()=>{
WelcomePackage.OnAddCharacter( (c) => {
sendChat('',`Got Character: ${c.get('name')}`);
});
});
```
> Welcome Package: Added OnAddCharacter() observer

- WelcomePackage/1.3/script.js
- WelcomePackage/script.json
Fixed Charactermancer bug in Welcome Package.
> Welcome Package v1.3

- WelcomePackage/1.3.1/script.js
- WelcomePackage/script.json
Fixed some timing issues in Welcome Package.
> Welcome Package v1.3.1

- Shadow of the Demon Lord/0.1/sotdl.js
- Shadow of the Demon Lord/script.json
First pass at API commit that will be required for newer version of the character sheet. Currently there is no API folder for Shadow of the Demon Lord but I have stepped up to write code.
> First Pass

- PowerCards/3.8.8/PowerCards.js
- PowerCards/script.json
Promoting lastest development version to OneClick Install
> Update PowerCards to 3.8.8

- COFantasy/1.06/COFantasy.js
- COFantasy/1.06/doc.html
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/doc.html
No change of version number yet.
> COFantasy: added support for combat manoeuvres.

- Yatzoid/README.md
- Yatzoid/Yatzoid.js
- Yatzoid/script.json
Basic implementation of the Yatzoid backend script.
> Yatzoid backend script

- COFantasy/1.08/COFantasy.js
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/README.md
to cope with the new Roll20 editor.
(no new version)
> COFantasy: update the handout parsing for team handouts

- COFantasy/1.08/COFantasy.js
- COFantasy/1.08/doc.html
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/doc.html
The script now correctly scans the new attack section for NPC, and the Hit points attribute in that view.
> COFantasy: update to take into account the new NPC view of the sheet

- Game Timer/1.0/timer.js
- Game Timer/script.json
- Game Timer/timer.js
This is a simple script to court how long does player use the game room. Just upload a clock picture on the table and name game.clock. Then the picture will court the time. API sandbox will shutdown soon when all player exit the room. Support for multiple clock at same time.
Demo:
https://media.giphy.com/media/p3UdAFAiVPZTo8zDXu/giphy.gif
> Game Timer

- HealthColors/1.6.0/HealthColors.js
- HealthColors/script.json
Timeout on large token set fixed.
> 1.6.0 Changes

- .gitignore
- PowerCards Macro Helper/1.0.5/PCMHelper.js
- PowerCards Macro Helper/script.json
- PowerCards/3.8.11/PowerCards.js
- PowerCards/script.json
Update PowerCards to version 3.8.11 and introduce a new ancillary addon called PowerCards Macro Helper, which automates PowerCard creation for 5E OGL games.
> Update PowerCards and Introduce PowerCards Macro Helper

- Pathfinder PCGen Import/PCGenPFImport.js
Changed split string for gmnotes and added an additional replace to remove some extraneous characters. Changed HP to Bar 1.
Apologies if this is not the proper way to do this. I have limited experience with javascript and github. I couldn't even tell you why my fix works.
> Edited PCGenPFImport script to work again

- Darker Dungeon/DarkerDungeon.js
- Darker Dungeon/script.json
For Giffy's Darker Dungeon version 2.0
> Darker Dungeon API

- Cypher Systems by Roll20 Companion/1.0/cypher_systems_by_roll20.js
- Cypher Systems by Roll20 Companion/script.json
> Cypher Systems by Roll20 Companion

- HeroLabImporter/1.0.4/HeroLabImporter.js
- HeroLabImporter/HeroLabImporter.js
- HeroLabImporter/script.json
Script Info: https://wiki.roll20.net/Script:HeroLabImporter
Source Code for Exporter: https://github.com/Imper1um/Roll20HLCE
> Adding in HeroLabImporter v1.0.4

- Terrain Generator/0.1.0/terrain-generator.js
This should allow for processing inline rolls.
added block from: https://wiki.roll20.net/API:Cookbook#processInlinerolls
> Process inline rolls - Terrain Generator

- tokenFate/script.json
- tokenFate/tokenFate.js
Token Fate script and json.
Randomly selects a token from the selected group by writing its name to chat.
> tokenFate Initial Commit

- Health Status/0.1/healthCommand.js
- Health Status/README.md
- Health Status/script.json
> New Script: Health Status

- DifficultyRating/1.03/DifficultyRating.js
- DifficultyRating/DifficultyRating.js
- DifficultyRating/README.md
- DifficultyRating/script.json
Adds version 1.03 of Difficulty Rating to the roll20 repo.  This is my first direct contribution to the API script repo, so I may have missed something.
- Previously, it was maintained in a gist: https://gist.github.com/VoltCruelerz/ce191b4823de0a57bebf6b924955c001
- User: https://app.roll20.net/users/1583758
- Forum Thread: https://app.roll20.net/forum/post/7542136/script-difficulty-rating-5e-encounter-calculator
> Add Script: Difficulty Rating

- Wrath And Glory/3.0/WrathAndGlory_DieRoller.js
- Wrath And Glory/Readme.md
- Wrath And Glory/script.json
Added new feature to Wrath And Glory/WrathAndGlory_DieRoller.js to identify if a test generated Ruin, Glory, Complication, and/or Critical.  No changes to existing capability.
Files updated:
1) readme.md
2) sheet.json
3) added folder 3.0
4) added WrathAndGlory_DieRoller.js in folder 3.0
All content is in unix EOL.
> Wrath And Glory DiceRoller version 3.0 

- HandsUp/.gitignore
- HandsUp/1.0.0/script.js
- HandsUp/Gruntfile.js
- HandsUp/README.md
- HandsUp/package.json
- HandsUp/script.json
- HandsUp/src/Commands.js
- HandsUp/src/Macros.js
- HandsUp/src/index.js
- HandsUp/src/utils/Chat.js
- HandsUp/src/utils/Colors.js
- HandsUp/src/utils/index.js
An accessibility script that allows shy or soft-spoken players to raise their hands to get the GM's attention.
> Hands Up v1.0

- ChatSetAttr/1.9/ChatSetAttr.js
- ChatSetAttr/ChatSetAttr.js
A maximum value of 0 would (wrongly) be treated as infinity.
> [ChatSetAttr] Fix bug in --mod option

- InitiativeTracker/script.json
- ModifyTokenImage/script.json
- psIsometricSuite/script.json
- vampire-v5/script.json
I found some syntax errors in the script.json files, and have fixed them.  I hope this is useful.
> Fix script.json errors

- Terrain Generator/0.1.1/terrain-generator.js
- Terrain Generator/script.json
TerrainGenerator is changing the msg object for chat messages, breaking the input to other scripts.
> Fix bug in Terrain Generator

- Savage Worlds Raise Roller/SavageWorldsRaiseRoller.js
- Savage Worlds Raise Roller/script.json
Initial version for the repository of the SW Raise Roller. Script provides rolling for Savage Worlds and displays a list of target numbers and if the roll would be a raise, success, or failure.
> Savage Worlds Raise Roller Initial

- COFantasy/1.11/COFantasy.js
- COFantasy/1.11/doc.html
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/doc.html
@clevett : I need your help. I noticed a few weeks ago that this script cannot be added (from Roll20 API library) anymore. It can be imported without any problem, but when using the "Add script" button, the API crashes (error message is `SyntaxError: Invalid or unexpected token`)
I cannot debug that on my own: the error message doesn't help, and I cannot even dichotomy the bug, since everything works fine on my side, and that would require sending tentative some script, let it be installed and look at the results, which only happens once a week, and would prevent users to use the normal version of the script.
The bug seems to trigger with all the versions I tried, by the way. Even the very first ones, which I know used to work.
> COFantasy: bug fixes and flying creatures grip attack

- Knight Styles Markers/1.0/Knight Style Marker.js
- Knight Styles Markers/script.json
First upload attempt for an API accompanying Knight's Roll20 sheet.
I hope I didn't do anything wrong.
> [Knight Style Marker] First Upload

- COFantasy/1.11/COFantasy.js
- COFantasy/1.11/doc.html
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/doc.html
@clevett : should I open a bug for the issue when adding this script?
> COFantasy: option for elixirs to cost mana.

- vampire-v5/VTM_Dice_Mechanics.js
Bug fix removing error checking which caused issues.
> Vampire the Masquerade 5th Edition API script.

- TokenCondition/0.1.0/TokenCondition.js
- TokenCondition/TokenCondition.js
- TokenCondition/script.json
Please add to One Click install!
```
tokencondition:
- "TokenCondition"
- "Tokens"
```
> Added 1 Script

- COFantasy/2.0/COFantasy.js
- COFantasy/2.0/doc.html
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/doc.html
and one more priest spell. Plus a new option for critical damages.
> COFantasy: support for more barbarian skills

- Shadowrun 5th Edition/1.01/shadowrun5e.js
- Shadowrun 5th Edition/README.md
- Shadowrun 5th Edition/script.json
- Redesign the api menu
- Include help & info in the chat
> Shadowrun 5th Edition v1.01

- CombatMaster/CombatMaster.js
- CombatMaster/script.json
Combat Master is an evolution of Combat Tracker, which I never posted to Roll20 and was a combination of Robin Kuiper's Combat Tracker and Status Info scripts.  Menus were added for control, as well as calls to external APIs and Macros during combat at various timing points or when conditions are added and removed.  In addition it integrates with libTokenMarker for custom icon support, group-init for rolling initiative,
> Combat Master v2.0

- Savage Worlds Raise Roller/SavageWorldsRaiseRoller.js
- Savage Worlds Raise Roller/SavageWorldsRaiseRoller.md
- Savage Worlds Raise Roller/script.json
- SavageWorldsStatusChanger/1.0.0/SavageWorldsStatusChanger.js
- SavageWorldsStatusChanger/SavageWorldsStatusChanger.js
- SavageWorldsStatusChanger/SavageWorldsStatusChanger.md
- SavageWorldsStatusChanger/script.json
- TurtleDraw/1.0.0/TurtleDraw.js
- TurtleDraw/TurtleDraw.js
- TurtleDraw/TurtleDraw.md
- TurtleDraw/script.json
Added markdown for Savage Raise Roller.  New TurtleDraw and Savage Worlds Status Changer.
> New API Scripts

- Shadowrun 5th Edition/1.02/shadowrun5e.js
- Shadowrun 5th Edition/script.json
* Bug fix on Group init
* Bug fix on the counter for missing attribute
> Shadowrun 5th Edition API v1.02 - Hotfix please if anyone is watching

- SavageWorldsStatusChanger/1.0.0/SavageWorldsStatusChanger.js
- SavageWorldsStatusChanger/SavageWorldsStatusChanger.js
- SavageWorldsStatusChanger/SavageWorldsStatusChanger.md
- SavageWorldsStatusChanger/script.json
Creating new API script: SavageWorldsStatusChanger.
> Savage Worlds Status Marker

- Earthdawn (FASA Official) character sheet companion/01.001/Earthdawn.js
- Earthdawn (FASA Official) character sheet companion/script.json
Earthdawn (FASA Official) companion
New version with new features.
> Earthdawn v01.001

- Shadowrun 5th Edition/1.02/shadowrun5e.js
- Shadowrun 5th Edition/script.json
> Shadowwrunv1.02

- Earthdawn (FASA Official) character sheet companion/01.002/Earthdawn.js
- Earthdawn (FASA Official) character sheet companion/script.json
The merge from last week (Earthdawn by FASA version 01.001) was only semi-successful. 
If you go to the script library, choose this script, and "ADD" the script, you get the dropdown asking if you want to run the latest version, version 01.001, or version 01.000.  No matter which of these three you choose, you always run 01.000.  Since it is the oldest version, the newer features do not work. 
If you instead of Adding the script instead "Import" it, it correctly imports 01.001, the latest version. 
I would not normally have assigned the few bugfixes and minor features I did this week a whole new version, but none of my messages about this versioning problem has gotten any  response, so I am trying to make yet another version in hopes that this one will take. 
I am fairly positive my json …
> Earthdawn by FASA character sheet companion   Verson 01.002

- AgoneDice/0.2/AgoneDice.js
- AgoneDice/AgoneDice.js
Hi,
I just forgot to increment the version...
Thank you!
> Version increment was forgotten

- Earthdawn (FASA Official) character sheet companion/01.002/Earthdawn.js
> Earthdawn by FASA V1.0021

- Earthdawn (FASA Official) character sheet companion/01.002/Earthdawn.js
> Earthdawn by FASA character sheet companion update 1.0022

- WelcomePackage/.gitignore
- WelcomePackage/1.3.2/script.js
- WelcomePackage/1.3/script.js
- WelcomePackage/Gruntfile.js
- WelcomePackage/package.json
- WelcomePackage/script.json
- WelcomePackage/src/script.js
Fixed some issues with the Welcome Package script's macro.
Also implemented Grunt-based build structure for the script.
> Welcome Package v1.3.2

- Earthdawn (FASA Official) character sheet companion/01.002/Earthdawn.js
Last week update 1.0022 was apparently merged into master (and github shows those updates), but the changes never went live to the public.
both this update, and the last several updates are not creating a new version (new number in script.json file), but are just being merged into the file for 01.002. This worked OK for version 01.0021, it just merging it into 01.002 and went live to the public, but for some reason, last weeks update of 1.0022 just seems to have disappeared, and are not part of the code being run now. Latest version runs code that self-identifies as being version 1.0021.
> Earthdawn by FASA update 1.0023

- DupCharToken/1.03/DupCharToken.js
Update   1.031 May 2020  Chris D.   Bugfix with copying bio and gmnotes.
> CharDupToken Update 1.031

- ShortRest/0.1.0/ShortRest.js
- ShortRest/readme.md
- ShortRest/script.json
Allows clicking of Hit Dice on 5e OGL to update health, hit dice counter, class, other & repeating resources and spell slots for those that reset on Short Rests
> Short Rest v0.1.0

- TokenMarker/1.0.0.0/TokenMarker.js
- TokenMarker/TokenMarker.js
- TokenMarker/script.json
Initial version of the TokenMarker library
> Adding TokenMarker library

- UniversalVTTImporter/0.1.0/UniversalVTTImporter.js
- UniversalVTTImporter/UniversalVTTImporter.js
- UniversalVTTImporter/script.json
Please add to the Approved.yaml!
> Added 1 Scripts

- ChangeMap_CloneTokens/ChangeMapCloneTokens.js
- ChangeMap_CloneTokens/script.json
Script created to clone PC tokens when changing maps
> create ChangeMap - CloneTokens

- approved.yaml
Keith reports that he fixed the issues that require these be commented out.
> Add two scripts

- HuntersMark/README.md
- HuntersMark/huntersmark.js
- HuntersMark/script.json
New script, to let you mark a target and automatically unmark previous targets.
Please add this to the One-Click Library.
> SCRIPT Hunter's Mark

- GoFish!/README.md
- GoFish!/go-fish.js
- GoFish!/script.json
fresh PR with an updated README.
> GoFish! by theTexasWave - a Roll20 Fishing minigame

- GoFish!/README.md
- GoFish!/go-fish.js
- GoFish!/script.json
sorry for an enhancement as soon as you approved, but thank you for the approval!
> fixed a bug, added documentation for new XP and RodDurability systems

- Shadowrun 5th Edition/1.02/shadowrun5e.js
Fixes several minor and major bugs, including the apiMenu appearing in chat whenever a chat was sent, Initiative Counter placement if it was added after someone had rolled initiative and problem with the turn order not sorting properly if more than one person used --rollInit in a turn. Added extensive documentation and some spelling corrections.
> Shadowrun 5e API Update

- Shadowrun 5th Edition/1.02/shadowrun5e.js
Very minor fix that was crashing the API
> [Shadowrun 5e] Update shadowrun5e.js

- HealthColors/1.6.1/HealthColors.js
- HealthColors/script.json
After copying a game, handleToken can be called before on('ready'). 
For details see https://app.roll20.net/forum/post/9091508/aura-slash-tint-healthcolors-script-does-not-work-in-copy-of-game/?pageforid=9094787#post-9094787 
Added a check on the state in handleToken (minimal change)
> Fix for error after copy game

- ChatTurnManager/0.0.1/ChatTurnManager.js
- ChatTurnManager/ChatTurnManager.js
- ChatTurnManager/README.md
- ChatTurnManager/script.json
A script to simplify Turn Order Management, and move it into chat.
> Add ChatTurnManager 0.0.1

- MapChange/1.4/MapChange.js
- MapChange/MapChange.js
- MapChange/script.json
Update script to v1.4 to fix a bug in the getPlayerIdFromDisplayName function causing player names that contain " (GM)" to not be processed correctly.
> Update MapChange to v1.4 to fix a reported bug

- COFantasy/2.09/COFantasy.js
- COFantasy/2.09/doc.html
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/doc.html
Mostly bug fixes, and a few display improvments.
> COFantasy: bug fixes.

- COFantasy/2.09/COFantasy.js
- COFantasy/2.09/doc.html
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/doc.html
Some improvements for luck and skills that need to re-do an attack.
> COFantasy: added 2 more warrior and barbarian skills. 

- Deal-Init/1.2/Deal-Init.js
- Deal-Init/README.md
- Deal-Init/script.json
Savage Worlds Initiative Dealer
> added Deal-Init

- Shadowrun 5th Edition/1.1/shadowrun5e.js
- Shadowrun 5th Edition/README.md
- Shadowrun 5th Edition/Tech Notes.md
- Shadowrun 5th Edition/script.json
* Refactor some code
* Made init roller account for wounds toggle
* Reverted a bar change
* Created a notes log for devs
> Shadowrun 5th Edition v1.1

- Deal-Init/1.3/Deal-Init.js
- Deal-Init/script.json
Added 4 joker deck support
added global config
> DealInit r1.3

- Teleport/1.0/teleport.js
- Teleport/script.json
Created teleport.js and associated description files and file structure to include on one-click repository.
> Created teleport.json entry

- COFantasy/2.15/COFantasy.js
- COFantasy/2.15/doc.html
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/doc.html
Plus a few bug fixes and qol improvements.
> COFantasy: added aura effects.

- Drunk/script.json
name now shows what system it is used for
> [Drunk] update menu name

- GMSheet/script.json
name now shows what system it is used for
> [GMSheet] update menu name

- DifficultyRating/script.json
name now shows what system it is used for
> [Difficulty Rating] update menu name

- TreatWounds/script.json
- TreatWounds/treatwounds.js
Initial public release of TreatWounds for Pathfinder 2E
> 1.0 Release of TreatWounds for Pathfinder 2E

- TreatWounds/script.json
- TreatWounds/treatwounds.js
changed version number in script, removed previousversion from script…
> No changes to script, just "housekeeping"

- .github/pr.json
- .github/workflows/validate_script_json.yml
- results.txt
- script.json.schema
- validate.sh
Added a JSON Schema (standard) that can be used both by third-party script developers as well as internal developers to ensure quality and reliability of the script.json files.
> Added a JSON schema for validation

- COFantasy/2.16/COFantasy.js
- COFantasy/2.16/doc.html
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/doc.html
Plus a number of improvements and bug fixes.
> COFantasy: more spells for monks, necromancers and bards

- MutantYearZero_SectorGenerator/0.1.0/sector-generator.js
- MutantYearZero_SectorGenerator/README.md
- MutantYearZero_SectorGenerator/script.json
- MutantYearZero_SectorGenerator/sector-generator.js
Huge timesaver when running MYZ game and you want to really focus on random sectors in hexcrawl for emergent play style.
> Adding Mutant Year Zero Sector Generator script

- PowerCards Macro Helper/1.0.12/PCMHelper.js
- PowerCards Macro Helper/script.json
- ScriptCards/1.0.9/scriptcards.js
- ScriptCards/script.json
New features and bug fixes for ScriptCards
Bug Fix for PCMHelper for missing dash in level 2 casting macro.
> Update ScriptCards to 1.0.9 and PCMHelper to 1.0.12

- COFantasy/2.16/COFantasy.js
- COFantasy/2.16/doc.html
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/doc.html
> COFantasy: more necromancer spells

- Starfinder Guidance/guidance.js
Please let this fix the One-click issue
> Another attempt to figure out what is wrong with One-click

- Starfinder Guidance/script.json
Jeff L identified an issue with the length of the original Name.
> Shorten Name for Roll20

- AgoneDice/0.4/AgoneDice.js
- AgoneDice/script.json
New version to go with sheet v0.8
> AgoneDice v0.4

- ClockTokens/1.1/ClockTokens.js
- ClockTokens/READEME.md
- ClockTokens/script.json
ClockTokens v1.1: Changed logic to accommodate multi-GM games or games where the creator is not a GM.
> ClockTokens: Accommodated multi-GM games and games where the creator is not a GM.

- COFantasy/2.17/COFantasy.js
- COFantasy/2.17/doc.html
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/doc.html
Quite a bit of new NPC capacities support, and PC heroic skills.
Improved invisibility
Support for alias and revealing NPC names.
> COFantasy: more skills, improved invisibility, bug fixes.

- COFantasy/2.17/COFantasy.js
- COFantasy/2.17/doc.html
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/doc.html
- COFantasy/doc_start.html
And fixed a number of issues with skills.
> COFantasy: removed message on Adding the script

- COFantasy/2.17/COFantasy.js
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
We'll see the result with the 'Add' button.
Contains also a couple of fixes for invisibility.
> COFantasy: escape all accented characters.

- WFRP4ePL/1.0.0/WFRP4ePL.js
- WFRP4ePL/Help.txt
- WFRP4ePL/script.json
Polish translation plus tweaks of Seth Williams' script for rolling critical hits
> Polish version of WFRP4e script to speed up critical hits rolling 

- AddCustomTurn/0.1.1/AddCustomTurn.js
- AddCustomTurn/AddCustomTurn.js
- AddCustomTurn/script.json
PLEASE ADD TO THE 1-CLICK LIBRARY!
> Added AddCustomTurn.  (Add to 1-click, please!)

- COFantasy/2.18/COFantasy.js
- COFantasy/2.18/doc.html
- COFantasy/COFantasy.js
- COFantasy/doc.html
HTML entities introduced bugs. Would be best if Roll20 could keep utf-8 when installing the script in the library...
> COFantasy: use hex code instead of html entities for accents.

- Roll20-Audio-Master/script.json
* description now has proper instructions and link to further documentation
* fixed the authors /roll20id sections to be correct
> Audio Master, update script.json 

- COFantasy/3.02/COFantasy.js
- COFantasy/3.02/doc.html
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/doc.html
In addition to bug fixes, changed the interface for riding a mount, option to draw a weapon as part of an effect, and a function to help importing Patfinder 1 characters (not complete, but should give a good starting point).
> COFantasy: helper function to import Pathfinder characters.

- SafetyToolsAlert/0.50/safety_tools_alert.js
- SafetyToolsAlert/README.md
- SafetyToolsAlert/safety_tools_alert.js
- SafetyToolsAlert/script.json
A simple tool to send a message to the GM and optionally play a sound from the jukebox if a Safety Tools card or token is placed on the VTT.
> Add API Script SafetyToolsAlert

- RatWorkshop_Barbarian/0.2/barbarian.js
- RatWorkshop_DungeonMasterTools/0.2/dungeon_master_tools.js
Fix how DM Tools and Barbarian Module Apply Version updates to settings
Refactor Campaign and Token change listeners
> Add feature to apply a small aura to the active tokens

- Earthdawn (FASA Official) character sheet companion/01.002/Earthdawn.js
- Earthdawn (FASA Official) character sheet companion/02.000/Earthdawn.js
Minor bugfixes and a few small features requested. 
This merges in release 2.0.  Also a few updates to V01.002 that never got published to github and should have been.
> Earthdawn FASA Official character sheet companion V2.01

- COFantasy/3.04/COFantasy.js
- COFantasy/3.04/doc.html
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/doc.html
Implemented special abilities for semi-ogres. Plus one new gnome ability, and a few bug fixes.
> COFantasy: semi-ogre abilities.

- COFantasy/3.04/COFantasy.js
- COFantasy/3.04/doc.html
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/doc.html
Also some bug fixes, and a few improvements.
> COFantasy: better automatisation of the knight's interception

- Earthdawn (FASA Official) character sheet companion/02.000/Earthdawn.js
> Update Earthdawn (FASA Offical) character sheet companion

- Earthdawn (FASA Official) character sheet companion/02.000/Earthdawn.js
> Earthdawn character sheet companion V2.031 minor updates

- README.md
- add logo & counters for some repo stats(inspired from [Roll20/roll20-character-sheets](https://github.com/Roll20/roll20-character-sheets#readme)
- links to Community Wiki documentation & Help Center
- replaced outdated "email us" with "Help Center Request"-link
- additional comment to some places
> Root README - more info and links

- RandomTokenTinter/0.0.0/RandomTokenTinter.js
- RandomTokenTinter/RandomTokenTinter.js
- RandomTokenTinter/script.json
Initial release of RandomTokenTinter, an API to randomly apply tints to selected tokens from either a command-line list or a Rollable Table
> Initial Release of RandomTokenTinter

- Earthdawn (FASA Official) character sheet companion/02.040/Earthdawn.js
- Earthdawn (FASA Official) character sheet companion/script.json
> Earthdawn FASA Official v2.04 

- PowerCards/3.8.18/powercards.js
- PowerCards/script.json
Minor update to enclose on:chat:message inside an on:ready structure.
> Update PowerCards to 3.8.18

- COFantasy/3.04/COFantasy.js
- COFantasy/3.04/doc.html
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/doc.html
More abilities for thieves, clercs and better support for some other abilities.
> COFantasy: support for more abilities

- SafetyToolsAlert/safety_tools_alert.js
Added GM feedback to config changes.
> SafetyToolsAlert_v.51

- COFantasy/3.05/COFantasy.js
- COFantasy/3.05/doc.html
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/doc.html
Corrected a crash when swapping from two-handed weapon to weapon + shield.
Support for final explosion of elementals.
> COFantasy: corrected a crash

- COFantasy/3.05/COFantasy.js
- COFantasy/3.05/doc.html
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/doc.html
Necessary due to unannounced changes in the turnorder interface by Roll20. May be a temporary bug, but who knows how long it will take to be reverted.
> COFantasy: fix for turn orders

- HeroTracker/herotracker.js
Adding change and comments on what was changed.
> Page_id fix proposed by Steve K.

- COFantasy/3.05/COFantasy.js
- COFantasy/3.05/doc.html
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/doc.html
> COFantasy: skills for Felis.

- ImportHS6e/script.json
Latest version, fixes for one click NaN bug.
> Update to latest version

- InitiativeTrackerPlus/1.29/initiative_tracker_plus.js
- InitiativeTrackerPlus/README.md
- InitiativeTrackerPlus/script.json
Added some updates to allow more control over colors to overcome some issues with dark mode default colors.
> Initiative Tracker Plus v1.29 Dark Mode adjustments.

- Deal-Init/1.8/Deal-Init.js
- Deal-Init/README.md
- Deal-Init/script.json
// 1.8 fixed controlledby bug in PC/NPC token detection;
//     fixed bug in --quiet where it would toggle on/off
//     added --showComps to detect and flag clubs in initiative for dramatic task and chase complications
> Deal Init r1.8

- ClockTokens/1.2/ClockTokens.js
- ClockTokens/README.md
- ClockTokens/script.json
Removed chat reporting when a non-gm player attempts to use a !clocktokens command (when GM Only is true), and fixed the issue where ClockTokens would report on commands sent to other scripts. Also corrected .readme file.
> ClockTokens: Fixed reporting of blocked commands

- ScriptCards/1.7.6/scriptcards.js
- ScriptCards/script.json
Update ScriptCards to version 1.7.6
> ScriptCards 1.7.6

- FatePointDisplay/1.0.1/FatePointDisplay.js
- FatePointDisplay/README.md
- FatePointDisplay/script.json
Corrected an issue where the user options object (globalconfig) was not being loaded properly so the script was always running off the default.
Also changed the chat message for error to whisper to GM, and logged the user options to API Console just in case.
> FatePointDisplay: Fixed globalconfig not being loaded correctly

- FatePointDisplay/1.0.2/FatePointDisplay.js
- FatePointDisplay/README.md
- FatePointDisplay/script.json
Fixed user options which are checkboxes not being read correctly as they were treated as bools despite being passed as strings.
> FatePointDisplay: Fixed user options which are checkboxes not being read

- COFantasy/3.07/COFantasy.js
- COFantasy/3.07/doc.html
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/doc.html
Plus some minor qol improvements.
> COFantasy: bug fixes

- RoleMasterD100/1.0.0/RoleMasterD100.js
- RoleMasterD100/RoleMasterD100.js
- RoleMasterD100/script.json
Please commit to 1-click, as well.
> Production Release

- COFantasy/3.08/COFantasy.js
- COFantasy/3.08/doc.html
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/doc.html
Abilities for mage-warriors, corruption hunters, fantastic familiars, and priests of Arwendee.
> COFantasy: more prestige abilities.

- RPGMlibrary AD+D2e/1.3.00/libRPGMaster2e.js
- RPGMlibrary AD+D2e/libRPGMaster2e.js
Improved the description of the getAbility() library function.
> Improved Library Help Handout

- InitiativeTrackerPlus/1.29/initiative_tracker_plus.js
Added ability for players to use favorites to assign statuses to tokens they control 
Added ability for GM to view configured values
Added feedback when using -setConfig
> Initiative Tracker Plus - Added 3 new features

- COFantasy/3.10/COFantasy.js
- COFantasy/3.10/doc.html
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/doc.html
Fixed a number of bugs related to the turn tracker.
Implemented some of the spells for Morn.
Implemented more user-friendly management of helmet.
> COFantasy: bug fixes and spells for Morn

- HeroSystem6eHeroic_HDImporter/README.MD
Added a troubleshooting tip section to the readme file to help with import errors.
> [HeroSystem6eHeroic_HDImporter] Update to README.MD

- PathToWindowOrDoor/1.0/PathToWindowOrDoor.js
- PathToWindowOrDoor/script.json
my info
updated help & removed readme
moved file to reflect roll20 file scheme
send message to gm, restricted usage to gm for commands added script to repo to reflect roll20 fully
> PathToWindowOrDoor Initial version, retry

- Earthdawn (FASA Official) character sheet companion/03.000/Earthdawn.js
- Earthdawn (FASA Official) character sheet companion/script.json
Earthdawn V3.000   Lots of misc upgrades.
> Earthdawn V3.000

- OneRollEngine/0.3/matchingSets.js
Scripts were broken because these ended up in the wrong subfolders, woops.
> move these into their correct version folders

- checkLightLevel/checkLightLevel.js
- checkLightLevel/readme.md
- checkLightLevel/script.json
New script submission for the one-click: *checkLightLevel*
- script approximates light level percentage for the selected token(s)
- script checks daylight level and all non-blocked lightsources
- script does not modify the Campaign, only outputs to chat
More info in [forum post](https://app.roll20.net/forum/post/11312893/script-update-checklightlevel)
> [New script] - checkLightLevel

- vampire-v5/1.3/VTM_Dice_Mechanics.js
- vampire-v5/VTM_Dice_Mechanics.js
- vampire-v5/script.json
Fixed issue with overwriting the message object.
> Simple sound fix the aaron

- vampire-v5/1.3/VTM_Dice_Mechanics.js
- vampire-v5/VTM_Dice_Mechanics.js
- vampire-v5/script.json
The author forgot to put this in a sub directory and increment the version number.
> Vampire-v5: Added 1.3 version to Script Library

- checkLightLevel/0.5.0/checkLightLevel.js
> Update file structure

- Dynamic Lighting Tool/1.0.1/dltool.js
- Dynamic Lighting Tool/dltool.js
- Dynamic Lighting Tool/script.json
This was categorized under Utilities, making it hard to find. Please categorize it under "Dynamic Lighting"
> DLTool - New version and PLEASE CHANGE CATEGORY

- Dynamic Lighting Tool/1.0.2/dltool.js
- Dynamic Lighting Tool/dltool.js
- Dynamic Lighting Tool/script.json
- Faces/0.1.1/Faces.js
- Faces/Faces.js
- Faces/script.json
DLTool fixes an issue with tokens on transmogrified pages bearing bogus ids in the represents field. Faces had a bug that kept it from properly choosing a random face.
> DLTool and Faces bug fixes

- Dynamic Lighting Tool/1.0.3/dltool.js
- Dynamic Lighting Tool/dltool.js
- Dynamic Lighting Tool/script.json
Better handling of directional light and sight
> Dynamic Lighting Tool update

- Darker Dungeon/1.0/DarkerDungeon.js
fixed random number generation inside Darker Dungeons API
> fixing RNG in d6 etc functions

- MarkerManager/1.0/MarkerManager.js
Apparently having a version element in the script.json necessitates a version subdirectory
> Adding missing version directory

- GreaterInvisibility/0.1.0/GreaterInvisibility.js
- GreaterInvisibility/GreaterInvisibility.js
- GreaterInvisibility/README.md
- GreaterInvisibility/script.json
Adding new Mod:
GreaterInvisibility
- Converts tokens to multisided and adds "invisible" image to them automatically
- Adds token macro to toggle invisibility
> feat: add new MOD- GreaterInvisibility

- COFantasy/3.13/COFantasy.js
- COFantasy/3.13/doc.html
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/doc.html
Also added support for some magic items.
> COFantasy: implemented first expertise skill

- UDLTorchLight/0.1.0/UDLTorchLight.js
- UDLTorchLight/UDLTorchLight.js
- UDLTorchLight/script.json
New mod for simple lighting options for players for UDL.  Inspired by "Torch" but trimmed down to only support UDL lighting.
> feat: new MOD - UDLTorchLight

- autoButtons/0.8.0/autoButtons.js
- autoButtons/script.json
There were some version number and directory issues, this should be fixed.
> Fix AutoButtons 0.8.0

- SimpleSound/SimpleSound.js
- SimpleSound/script.json
Fixed issue where SimpleSound is changing the msg object and breaking other scripts.
> SimpleSound Msg Modification Bug

- SimpleSound/2.2/SimpleSound.js
- SimpleSound/script.json
Added missing 2.2 subdirectory with SimpleSound 2.2 in it.
> Simple sound2.2 fix

- COFantasy/3.13/COFantasy.js
- COFantasy/3.13/doc.html
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/doc.html
Implemented epic vitality, spells from the Way of Arwendée, epic healer spells, and higher level telepathy spells.
> COFantasy: implemented more epic powers.

- Dynamic Lighting Tool/1.0.8/dltool.js
- Dynamic Lighting Tool/dltool.js
- Dynamic Lighting Tool/script.json
With debugging help from the Aaron, this version also prevents crashing in circumstances where the selected object is not what the script expects to see.
> Dynamic Lighting Tool Code cleanup

- MonsterHitDice/script.json
Fixed an error in the global config stuff.
> Fixed typo

- ModifyTokenImage/1.0.5/modifytokenimage.js
If an handout had it's avatar image set from outside My Library, the attempt to set a tokens imgsrc to that avatars image path would cause the sandbox to crash.
> Fixing sandbox crash bug

- ClassActions/1.0.0/ClassActions.js
- ClassActions/script.json
Class Actions Mod by Kilzak
This is a mod that i'm creating to help lazy players with their class actions, have so far, paladin divine sense and rage for barbarian, the ideia is that the player can click on the sheet to send the trait to the chat and the mod will reconize and do the related actions.
like, reduce 1 for class_resources and mark rage dmg modifier, it uses ChatSetAttr as dependencie.
please let me know if any changes are needed :)
> [class-actions-mod] new mod V1.0.0

- COFantasy/3.15/COFantasy.js
- COFantasy/3.15/doc.html
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/doc.html
* Added better support for warrior specialization
* Improved stair management
* Fixed issue with latest version of the sheet.
> COFantasy: small fixes and improvements.

- ShowButtons/1.0.1/ShowButtons.js
- ShowButtons/ShowButtons.js
- ShowButtons/script.json
Initial Repo release of ShowButtons, which includes the "playerscanids" update to let players target characters they don't control.
> ShowButtons v1.0.1

- ScriptCards/2.7.8/scriptcards.js
- ScriptCards/script.json
> ScriptCards 2.7.8

- COFantasy/3.15/COFantasy.js
- COFantasy/3.15/doc.html
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/doc.html
Fixed a number of bugs, and added support for the latest changes in the associated sheet.
> COFantasy: update for custom slots on the sheet.

- COFantasy/3.15/COFantasy.js
- COFantasy/3.15/doc.html
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/doc.html
> COFantasy: fixed bug with weapons in hand.

- MapChange/1.8/MapChange.js
- MapChange/MapChange.js
- MapChange/script.json
Fix the parsing of incoming string to boolean for checkbox options
Move globalconfig debug option to be behind debug user option
> Fix for Boolean Parsing on OneClick Settings

- Earthdawn (FASA Official) character sheet companion/03.30/Earthdawn.js
- Earthdawn (FASA Official) character sheet companion/03.301/Earthdawn.js
- Earthdawn (FASA Official) character sheet companion/script.json
> V3.301 Earthdawn fasa official, minor patch

- Multi-World Calendar/1.2/mwcal.js
- Multi-World Calendar/mwcal.js
No version update, just quick fix
> Fixed small issue with Multi-World Calendar

- SheetDefaults/1.0.0/SheetDefaults.js
- SheetDefaults/SheetDefaults.js
- SheetDefaults/script.json
This is a new script. Please update the YAML.
Thank you!
> Releasing Sheet Defaults

- COFantasy/3.15/COFantasy.js
- COFantasy/3.15/doc.html
- COFantasy/COFantasy.js
- COFantasy/ChangeLog.md
- COFantasy/doc.html
Allows all animal form powers.
> COFantasy: add support for changing forms.

- DrD2StatusMarkers/script.json
Added a download link in description for the token marker set this script uses
> DrD2StatusMarkers – add token marker set link in description

- Earthdawn (FASA Official) character sheet companion/03.330/Earthdawn.js
- Earthdawn (FASA Official) character sheet companion/script.json
> v3.330 Earthdawn FASA Official character sheet companion. 

- WildShape/1.4.3/WildShape.js
Chat message on startup only to show in debug mode.
A suggested fix to the script in order to stop chat spam.
> Suggested fix to Wildshape

- ScriptCards/2.7.35/scriptcards.js
- ScriptCards/script.json
> ScriptCards 2.7.35

- Earthdawn (FASA Official) character sheet companion/03.430/Earthdawn.js
- Earthdawn (FASA Official) character sheet companion/script.json
> Earthdawn FASA Official V3.430

- ScriptCards/3.0.01/scriptcards.js
- ScriptCards/script.json
Fix bad internal numeric version number
> ScriptCard 3.0.01

- MagicMaster/4.0.4/MagicMaster.js
- MagicMaster/MagicMaster.js
- MagicMaster/magicMaster.js
* Fixed removeMIability() which was deleting across all sheets rather than just selected sheet.
> RPGM MagicMaster: removeMIability() fix

- ResourceTracker/0.5.6/ResourceTracker.js
- ResourceTracker/README.md
- ResourceTracker/script.json
Fixed script.json file with missing comma and one fix to ResourceTracker.js with create command.
> Resource tracker clean

- AttackMaster/5.0.4/attackMaster.js
- AttackMaster/attackMaster.js
* Copied the wrong version of the file to be pushed!  Needs urgent merge to fix fatal crash!
> Very urgent! AttackMaster v5.0.4 Fix critical error - parentheses on calculation
