AmmunitionTracker/AmmunitionTracker.js, AmmunitionTracker/help.txt, AmmunitionTracker/package.json
Used to track ammunition with a group of commands utilising slots. Ironically is incompatible with my GMCode script.
=> AmmunitionTracker

README.md
Hopefully the wiki guide is sufficient for most users to manage submitting things to GitHub. Several have already benefitted for character sheets, so I figure linking to it from the readme on the API repo would be useful, instead of implying your only recourse for learning was emailing the developers.
=> Add link to GitHub guide on wiki

Its A Trap/ItsATrap.js, Its A Trap/README.md, Its A Trap/package.json, Token Collisions/TokenCollisions.js, Token Collisions/package.json, Vector Math/VecMath.js, Vector Math/package.json
Added It's A Trap, Token Collisions, and Vector Math scripts (all related).
=> It's A Trap, Token Collisions, Vector Math

Its A Trap/README.md
Fixed dependency listing (script depends on Token Collisions, not Collision Detection) and fixed link to Vector Math
=> Update It's A Trap! README.md

GUMSHOE/GUMSHOE.js, GUMSHOE/HELP.md, GUMSHOE/package.json
This script is designed to be used with my [GUMSHOE Trail of Cthulhu character sheet.](https://github.com/Roll20/roll20-character-sheets/tree/master/Gumshoe_TrailOfCthulhu). It implements the custom roll buttons in the sheet. *(GUMSHOE uses a point spending system, not just dice rolling, so every roll modifies character sheet attribute values)*
The script is generic enough that it can support all GUMSHOE system games, if the character sheets are created.
Note to @rileydutton or who does the merging: bundled in the script are a few dependencies. They are *each* MIT licensed, so there's no copyright issue. Eventually (read: next few months) I'll spin these out into their own scripts and include them in this repo. But they need some more love first before they're generally usable. Please …
=> GUMSHOE: Add new GUMSHOE point spending engine

EotE Dice Roller/EotE-Dice.js, EotE Dice Roller/package.json
-Added debug logging to API console.
-Extra dice will be added automatically when weapons are damaged
-Negative dice can now be used in the character sheet.
*EXAMPLE* If the GM has 2 setback dice in the GMPool, the player can put
-1blk in the dice text box, or -1 in the players dicepool and the script
will do the subtraction for you.
=> Version 2.6

Numenera_Natha/Help.txt, Numenera_Natha/Numenera_Natha.js, Numenera_Natha/package.json
4.2: stat rolls can be called by macros and a selected character token.
See the !nathanum-macroroll chat command.
Plus added assets handling to stat roll.
=> 4.2: stat rolls from macro and assets handling

Numenera_Natha/Numenera_Natha.js
Skill level added to the roll parameters.
=> v4.3 : Skill level added to the roll parameters.

ExtendedExpressions/Help.txt, ExtendedExpressions/extend.js, ExtendedExpressions/package.json
Add '==' operator (synonym for '=' operator).
Add abs, ceil, floor, round, max, and min functions.
Finish plumbing error-reporting through to the user.
=> ExtendedExpressions v0.4 improvements

Ammo/Ammo.js, Ammo/package.json
Removed dependency on isGM script.
=> Ammo: Updated to version 0.3.0

CommandShell/package.json, CommandShell/shell.js, cron/cron.js, cron/package.json
Also use new functionality to default cron to execute as user who scheduled job.
=> Pass speakingAs through to handlers in wrapped sendChat.

cron/Help.txt, cron/cron.js, cron/package.json
Also improve support for jobs on counts outside the range present in the tracker (e.g. tracker contains entries on counts 10, 5, and 3, and a cron job is scheduled to go off on count 0).
=> Add -A/--advance argument to advance initiative-based jobs by N rounds

Its A Trap/ItsATrap.js, WorldMapDiscovery/README.md, WorldMapDiscovery/WorldMapDiscovery.js, WorldMapDiscovery/package.json
There was a bug involving tokens representing characters which caused the script to get the wrong character coordinates for detecting collisions with traps. 
Whenever a character token's status bar changed, it would fire a change event for every instance for that character's token on every map they're present on. This was causing the script to sometimes try a collision between the character on another map and with a trap on the current map whenever the tokens' status bars change. 
This was fixed by restricting the script to only check collisions for character tokens on the players' current page.
=> Fixed same-map bug in 'Its A Trap' script AND new World Map Discovery script.

Ryuutama Skill Check Totaler/package.json, Ryuutama Skill Check Totaler/ryuutama-check-totaler.js
Adding script to automatically total Ryuutama skill checks made with the Ryuutama character sheet since that ability cannot be done on the character sheet itself due to how critical successes are calculated.
=> Ryuutama Skill Check Totaler

PathMath/1.1/PathMath.js, PathMath/1.2/PathMath.js, PathMath/script.json, PathSplitter/1.0/PathSplitter.js
PathMath 1.2 includes the following updates:
* toSegments now converts quadratic bezier curves used in freehand paths into tiny line segments. 
* Implemented tupleToPoint() which converts a _path tuple into a 2D homogenous point in map coordinates.
* Implemented getTransformInfo() which gets the data from a path relevant to computing its affine transform.
* mergePathStr() can now handle rotated paths. Quadratic freehand paths are converted to polygonal paths when they are merged.
Path Splitter now supports freehand paths thanks to the above updates.
Custom Status Markers now supports rotated paths thanks to the above updates.
=> PathMath 1.2

TotalRolled/TotalRolled.js, TotalRolled/script.json
This API will automatically total all rolled die and modifiers then return it to the chat box. It will also return the number of stunt points the user rolled on the previous roll. If this API is used with the new Titansgrave character it will also return if the user hit the target number that a spell requires to be casted.
=> Adding an API for Titansgrave

RollableTableMacros/1.0/RollableTableMacros.js, RollableTableMacros/RollableTableMacros.js, RollableTableMacros/script.json
This is a simple script that gets an item from a rollable table and enters its name as a chat message rather than showing it as a rollable table result. This allows use of most of the normal features of text chat such as dice rolls, inline rolls, macros, etc. A notable exception is roll queries, which aren't currently supported.
This will select an item at random from the table, respecting each item's weight. The item's icon, if any, is ignored.
=> Rollable table macros

COFantasy/README.md, COFantasy/script.json, MarchingOrder/2.1/marchingOrder.js
I'd like to add the link to the full documentation in the script.json of COFantasy (and use pseudo for author).
I also committed a small bugfix to MarchinOrder
=> Added link in script.json

OneRollEngine/0.1/matchingSets.js, OneRollEngine/README.md, OneRollEngine/script.json
Provides support for One Roll Engine and other systems that rely on matching sets.
The primary usage is via a user config on the script, which tells it to find sets in any dice pools of a given size (it defaults to d10's). It also provides a roll modifier and API command using the standard "!mod" format, in this case `!sets`. GM Roll support is included, and it intentionally does not interact with inline rolls.
I'd suggest this be placed as a System Toolbox for One Roll Engine, or perhaps as a Chat script if people think it might be more generally useful. Other uses I can think of:
- There are a few other obscure systems like Mistborn RPG that also use matching mechanics.
- Could be used to simulate poker-like card games: `/roll 5d13 !sets` would simulate a poker hand.
Sample output: …
=> Add One Roll Engine style grouped dice sets

Bloodied and Dead Status Markers/Bloodied and Dead Status Markers.js, TurnMarker1/TurnMarker1.js
- Previously, it would fire when HP was edited, or the token rotated, etc. This limits how often the code runs for performance.
=> limit checkForTokenMove to when the token is moved.

5th Edition OGL by Roll20 Companion/1.4/5th Edition OGL by Roll20 Companion.js
With the charactermancer update, the global save modifier field has been added to the death saving throw template by default, even when no global save modifier is used ( {{global=}} ). This is causing the companion script to think that the is a global modifier roll, but errors because no roll is found.  This update will ensure that the handledeathsave method only triggers when there actually is a roll in the global save field.
=> Fixed death saving throws being triggered.

Wrath And Glory/2.1/WrathAndGlory_DieRoller.js, Wrath And Glory/Readme.md, Wrath And Glory/script.json
Corrected a bug in the die roller.  When a damage roll is rerolled the additional successes were not being added to the existing damage roll correctly.
This release includes the addition of three lines of code to an existing function within the js file, updates to the changelog (readme) to reflect the change, and updates to the json file including the version numbers.
The js file update includes the creation of the 2.1 folder.
All files verified to be using the unix EOL prefix.
=> WAG Die Roller 2.1 - Damage Roll Fix

Flight/3.5/Flight.js, Flight/script.json
Roll20 recently (a while back now, in all honesty) reversed the order the status markers get rendered. They're now drawn in the "correct" order, so we no longer need to reverse our symbols.
Closes issue #771.
=> [Flight] Fix numbers appearing in reverse order

DeltaGreenRPGCompanion/1.5/DG_companion.js, DeltaGreenRPGCompanion/delta_green_companion.json
Allow autocomputation of projection on bonds when the player use the roll button. Without it, the change has to be done manually using the proj box.
=> Companion API for the unofficial Delta Green Sheet

Earthdawn (FASA Official) character sheet companion/01.000/Earthdawn.js
- Selecting 'Vague Success (not recommended)' now returns 1
- Selecting 'Full' now returns 0
=> [Earthdawn (FASA Official)] Fixed result style menu enum map

WildShapeResizer/0.0.1/WildShapeResizer.js, WildShapeResizer/README.md, WildShapeResizer/script.json
A script to automatically resize a Rollable Table Token when a different side is chosen. It does this by repurposing the “weight” attribute of the Items in the Rollable Table. It was written with D&D Druid Wild Shape tokens in mind, but would work for any square rollable table tokens from which players will choose different sides.
The script listens to `token:change` events, looks for a table with the same name as the token, and updates the token size when the side changes, so no other configuration should be required.
=> Add WildShapeResizer to automatically resize Rollable Table Tokens

AgoneCleanOlds/1.0/AgoneCleanOlds.js, AgoneCleanOlds/AgoneCleanOlds.js, AgoneCleanOlds/script.json
This API script allows to clean all olds attributes from Agone-(french) v0.1 after using the conversion button in the help section's new sheet.
=> API script to clean old attributes from Agone-(french) v0.1

WildShapeResizer/0.0.2/WildShapeResizer.js, WildShapeResizer/script.json
Version 0.0.2 fixes the following:
* Tokens copied from one map page to another throw errors until they are reset by selecting (or rolling) another side from the table.
* Tokens are resized to 0×0 when on a map without grid snapping
Cleanup:
Migrate to using ES6 const/let declarations, to make clear which variables actually vary.
=> Fix two bugs in WildShapeResizer

Fumbler/0.2.0/Fumbler.js, Fumbler/README.md
**Purpose:**  Fix fumbler issues found in #993  
**Causes:**  README is misleading users and dice rolls assume custom fumbler tables will always have a high of 100.  
**Changes:**   Updated the README to use valid JSON, and added some examples of good and bad custom fumbler tables. I also bounded the dice rolls when using a custom fumbler table to the max value of that table and added a utility function that would sort the fumbler table by their 'low' attributes. 
In the process of these changes, I realized that the text parsing for custom fumbler tables would fail if one used the tab character in their custom fumbler tables, so I updated the text parsing to account for that as well and figured I'd put it in this PR since it was only one line changed. 
Closes #993
=> Fumbler: Increase robustness and updated README

approved.yaml
The It's a Trap Burn Bryte theme script never got added to approved.yaml when the initial PR for it was merged. I'd like it to be added to the One-Click library, please.
=> approved.yaml - It's a Trap Burn Bryte theme

approved.yaml
`WildHelpers` is a dependency for `WildShape`.  Not having it in the approved file prevents the 1-click install of `WildShape` from working.
re: https://app.roll20.net/forum/post/9113273/one-click-install-dependency-not-working/?pageforid=9136675
=> Adding approved for WildHelpers

DSA4_1-CritChecker/1.0.0/dsa41-crit-checker.js, DSA4_1-CritChecker/README.md, DSA4_1-CritChecker/dsa41-crit-checker.js, DSA4_1-CritChecker/script.json
This Pull Request introduces a new API Script which can used together with the "Das Schwarze Auge 4.1".
It tries to overcome some missing game system mechanics related to talent rolls (which are quite complicated in the DSA game system and therefore are not fully covered by Roll20 roll template mechanics)
The Script is reacting to roll template messages in the chat and (in some situations) sends a message to all or some players. There are no manipulations of game/character states or attributes or something like this.
=> Introducing new DSA 4.1 Crit Checker API Script

approved.yaml
* fixes #950, per request of the author of the scripts.
* the generic 5E "It's a trap" have long existed as replacement for the two older API
=> Remove outdated API ItsATrap_theme_5E_OGL and Shaped

approved.yaml
There are several APIs that have been incorrectly labeled under "System Toolbox"(meant for APIs dedicated to specific rpg systems", as well as being filed under heavily overused "Utilities".
Changed a bunch of "Utilities" APIs to be more appropriately listed under "Tokens", "Chat", "Maps & Drawings", "Dynamic Lighting".
There would be a good reason to make more categories for APIs, here being my main suggestions:
- **Combat**, due to the large pile of Combat & Initiative APIs
- **D&D 5E**,due to the massive amount of APIs specialized for the system and to be compatible with the **D&D 5E by Roll20**-sheet
- **API Extension Libraries**, due to the number of APIs that aren't meant for users directly, but to be utilized by other APIs. Creating a separate category for them and listing them at …
=> Update Categories of several wrongly labeld APIs

Door Knocker/1.212/DoorKnocker.js
- Doors revealed by search are now made with a stroke_width 20px greater than the actual DL line to ensure they are visible in UDL
=> fixes for crashes and update to search revealed doors

TokenController/1.0.0/TokenController.js, TokenController/TokenController.js, TokenController/script.json
Allows DMs to create dynamic paths that are not map or position specific, but rather follow grid paths.
As of now, DMs will need to figure out the Path Code based on the clues until I build the Path Building tool.
Once a path is created (comes with 3 testing paths), the DM can select a token and start the pathing.
The interval is adjustable to help balance latency.
Multiple paths can be assigned to a token for intricate layered pathing.
Comes with full-control menu and macro to call menu at will.
Watches for object changes and removes from path when necessary.
Allows object Lock-in-Place and Following
=> Rebase off Dev

UnSanity/script.json
Please commit to the one-click.
UnSanity is a unicode sanitation checking script that lets users test various destinations around the Roll20 interface (chat, log, handouts) for any unicode sanitation that may interfere with what they want to do.
=> UnSanity Submission to 1-click

InitiativeTrackerPlus/1.29/initiative_tracker_plus.js
Quickfix to allow disabling of the MotD display every time the script starts.  Use '!itp -setConfig show_motd:false' to turn it off.  The callout with the ITP version number will continue however.
=> Initiative Tracker Plus - Quickfix allowing motd disabling, Bugfix re-added combat music capabilities

ImprovedCritical/1.0/ImprovedCritical.js, ImprovedCritical/ImprovedCritical.js, ImprovedCritical/READ.md, ImprovedCritical/script.json, WelcomePackage/Gruntfile.js
Improved Critical/Fumble Effect Generator
================================
**Critical**
Usage `!critical [percent]` where percent is a number between 1 and 100. If omitted a random percentage will be rolled.
Example:
`!critical`
**Fumble**
Usage `!fumble [percent]` where percent is a number between 1 and 100. If omitted a random percentage will be rolled.
Example:
`!fumble 86`
=> New API script ImprovedCritical that generates critical/fumble effects

Concentration/Concentration.js
- Bug fix: if the CON modifier was greater than the DC, the script would crash due to a negative number in the crit success/fail target in the dice roll - [R20 thread](https://app.roll20.net/forum/post/11050044/concentration-crashing#post-11066735)
- tokenMod integration: added TM observer so TM changes to hit points will now trigger Concentration script - [R20 thread](https://app.roll20.net/forum/permalink/11034532/)
=> Bug fix & tokenMod integration

Velvet Generation/script.json, Velvet Generation/vg.js
This is a support script for Velvet Generation, enabling some of the weird stuff we need to do with dice in that system. As the description says, it does the following:
* makes all d6 dice dragged onto the table from chat controllable by all players (players need to move dice around the tabletop, even if they were rolled by others).
* adds a command for `!amped`, which acts on all selected dice tokens and rerolls any that are set to 1, with a visual effect to indicate it.
* adds a command for `onFire|*` which acts on all selected dice tokens and sets all 1s to the number indicated by `*`, with a visual effect to indicate it.
=> initial commit of Velvet Generation support script

Velvet Generation/script.json
The `patreon` prop in `script.json` got left in from whichever one I copied as a template, so it's removed.
I didn't realize that `name` was the label that would be used in the API selector, so I added a space.
=> Fixed incorrectly-included patreon link

ListAttrs/listattrs.js, ListAttrs/script.json
An easy-to-use script to retrieve character sheet attributes from tokens on the current page, and emit them to chat.
=> [ListAttrs] Add version 1.0.0 of this new script

Dealer/script.json
Ten new templates for Supernotes
Bug fixes for Dealer
=> Supernotes and Dealer

DrD2LinkedTenacity/0.1.0/DrD2LinkedTenacity.js, DrD2LinkedTenacity/DrD2LinkedTenacity.js, DrD2LinkedTenacity/script.json
I would like to publish my script to the official Roll20 script respository. However, it is only designed for use with the Draci Doupe II sheet since it interacts with specific attributes. I wonder if it can be published under the "System Toolbox" category?
Please let me know if it is possible and also whether or not my script meets the requirements for publishing.
The script allows for changes made to an NPC's `tenacity_current` attribute to be propagated to a PC character's sheet if the PC has been designated as the NPC's owner, and vice versa. Think about it as heroes having companions where "tenacity" indicates how long the companion can last in a conflict. _Tenacity_ is my loose translation of the word _sudba_.
Also works for groups of enemy NPC's that should share the "tenacity" …
=> DrD2LinkedTenacity new script

DrD2StatusMarkers/0.1.0/DrD2StatusMarkers.js, DrD2StatusMarkers/DrD2StatusMarkers.js, DrD2StatusMarkers/script.json
I created a new API script for use with the Draci Doupe II sheet.
This script allows players to set token markers based on specific character attributes (`body_scarred`, `spirit_scarred`, `influence_scarred`, `danger` and `advantages`). Should also work the other way around, where token marker changes update the sheet attributes.
Since this script accesses token markers by their name, it only works for icons called `RED`, `GRN`, `BLU`, `BLK` and `VIO`.
=> DrD2StatusMarkers new script

Triggered Cleanup/script.json, Triggered Cleanup/v1.1/Release Notes.txt, Triggered Cleanup/v1.1/Triggered Cleanup.js
Two function calls were being called on every chat entry when they didn't need to be.
=> Efficiency improvement

HuntersMark/0.4.0/huntersmark.js, HuntersMark/README.md, HuntersMark/huntersmark.js, HuntersMark/script.json
Now supports the ability to mark multiple characters at a tie. Some characters need this.
=> Hunters-Mark

GameAssist/GameAssist.js, GameAssist/LICENSE, GameAssist/README.md, GameAssist/script.json
This pull request adds **GameAssist**, a modular API loader and automation suite for Roll20. GameAssist is designed for D&D 5E (2014 Character Sheet) but is extensible for other systems. This is the initial beta release.
**Features:**
- Modular loader: Enable or disable automation modules in real time.
- Core modules: CritFumble, NPCManager, ConcentrationTracker, NPCHPRoller (most require TokenMod).
- Priority-based task queue and watchdog for robust automation.
- In-chat configuration management (!ga-config), metrics dashboard, and error logging.
- State isolation per module and built-in compatibility checks.
**Installation & Requirements:**
- Requires a Roll20 Pro subscription for API sandbox access.
- Strongly recommended: Install TokenMod API for full marker automation.
- See the …
=> Add GameAssist: Modular Roll20 API Automation Framework (Beta)

Aziz Light!/1.0.0/aziz-light.js, Aziz Light!/README.md, Aziz Light!/aziz-light.js, Aziz Light!/script.json
This script is now ready for  primetime! It allows for fast adjustment of daylight settings via the dynamic lighting, as well as providing a smoothing lightening and darkening effect over time for "time passing"-like effect to maps.
This is my first of likely many more updates and submissions! I'm happy to respond & correct things if they appear.
=> New Script: aziz light!

Calendar and Weather/Calendar and Weather.js
Correct the code for split messages and don't whisper to the GM for the GM menus
=> Update Calendar and Weather.js
